name: Build and Release

on:
  push:
    tags:
      - 'v*'        # При создании тега v1.0.0, v1.0.1...
      - 'Layle_v_*' # При создании тега Layle_v_0.0.6...

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build Electron app
        run: npm run dist:win
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
